// <auto-generated />
using System;
using CL2TristanVela.Database.AlumnosContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CL2TristanVela.Migrations
{
    [DbContext(typeof(AlumnosContext))]
    [Migration("20231027225537_ActulizarDb")]
    partial class ActulizarDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CL2TristanVela.Database.AlumnosEntity", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoAlumno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreAlumno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAlumno");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("CL2TristanVela.Database.NotasEntity", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<string>("NombreCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("IdAlumno");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("CL2TristanVela.Database.NotasEntity", b =>
                {
                    b.HasOne("CL2TristanVela.Database.AlumnosEntity", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno");
                });
#pragma warning restore 612, 618
        }
    }
}
